# Generated by Django 3.1.2 on 2020-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201010_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='type0',
            field=models.CharField(choices=[('MEDINA0', 'Medina 0'), ('MEDINA1', 'Medina 1')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infomodel',
            name='type1',
            field=models.CharField(choices=[('CITY0', 'City 0'), ('CITY1', 'City 1')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infomodel',
            name='type2',
            field=models.CharField(choices=[('REGION0', 'Region 0'), ('REGION1', 'Region 1')], max_length=50, null=True),
        ),
    ]
