# Generated by Django 3.1.2 on 2020-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20201012_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='selection',
            field=models.CharField(choices=[('', 'None'), ('OPTION0', 'Option 0'), ('OPTION1', 'Option 1'), ('OPTION2', 'Option 2')], max_length=50),
        ),
    ]
