# Generated by Django 3.1.2 on 2020-10-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20201015_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='type0',
            field=models.CharField(blank=True, choices=[('MEDINA0', 'Medina 0'), ('MEDINA1', 'Medina 1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='type1',
            field=models.CharField(blank=True, choices=[('CITY0', 'City 0'), ('CITY1', 'City 1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='type2',
            field=models.CharField(blank=True, choices=[('REGION0', 'Region 0'), ('REGION1', 'Region 1')], max_length=50, null=True),
        ),
    ]
